default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME") { ENV.fetch("DB_USER", "postgres") } %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", ENV.fetch("DB_DATABASE", "app_development")) %>

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DB_NAME", "app_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", ENV.fetch("DB_DATABASE", "app_production")) %>
